version: '3.8'
services:
  
  devcontainer:
    container_name: sc-devcontainer
    build:
      dockerfile: Dockerfile
      target: devcontainer
    volumes:
      - '$HOME/.aws:/root/.aws'
      - '.:/workspace'
