version: '3.8'
services:
  
  devcontainer:
    command: tail -f /dev/null
    build:
      context: .
      target: base
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      # - '$HOME/.aws:/root/.aws'
      - '.:/workspace'
